import {Inter} from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/header";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { Github, Linkedin } from "lucide-react";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata = {
  title: "Careoch - AI Career Coach",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider 
      appearance={{
        baseTheme: dark,
      }}
      signInFallbackRedirectUrl="/onboarding"
      signUpFallbackRedirectUrl="/onboarding"
    >
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${inter.className} `}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            {/* header */}
            <Header />
            <main className="min-h-screen">
              {children}
            </main>
            <Toaster richColors />
            {/* footer */}
            <footer className="bg-muted/50 py-12">
              <div className="container mx-auto px-4 text-center text-gray-200">
                <div className="flex flex-col md:flex-row items-center justify-center gap-8">
                  {/* Dhruvin Oza */}
                  <div className="flex flex-col items-center">
                    <p className="font-semibold">Dhruvin Oza</p>
                    <div className="flex gap-4 mt-2">
                      <a href="https://www.linkedin.com/in/dhruvin-oza-617047282/" target="_blank" rel="noopener noreferrer" aria-label="Dhruvin's LinkedIn">
                        <Linkedin className="w-6 h-6 hover:text-blue-400 transition" />
                      </a>
                      <a href="https://github.com/Dhruvinoza17" target="_blank" rel="noopener noreferrer" aria-label="Dhruvin's GitHub">
                        <Github className="w-6 h-6 hover:text-gray-400 transition" />
                      </a>
                    </div>
                  </div>
                  {/* Vinit Patel */}
                  <div className="flex flex-col items-center">
                    <p className="font-semibold">Vinit Patel</p>
                    <div className="flex gap-4 mt-2">
                      <a href="https://www.linkedin.com/in/patel-vinit-57b2b336b?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app" target="_blank" rel="noopener noreferrer" aria-label="Vinit's LinkedIn">
                        <Linkedin className="w-6 h-6 hover:text-blue-400 transition" />
                      </a>
                      <a href="https://github.com/vinit-patel-2409" target="_blank" rel="noopener noreferrer" aria-label="Vinit's GitHub">
                        <Github className="w-6 h-6 hover:text-gray-400 transition" />
                      </a>
                    </div>
                  </div>
                </div>
                <p className="mt-8 text-xs text-gray-400">Made by Dhruvin Oza & Vinit Patel</p>
              </div>
            </footer>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
